version: '3'

services:

  #PHP Service
  app:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: php:7.4-fpm
    expose:
      - "9000"
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    links:
      - db
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=mysql
      - DB_NAME=tea
      - DB_USER=root
      - DB_PASS=
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=0
    ports:
      - "80:80"
    #  - "443:443"
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  #MySQL Service
  db:
    image: mariadb:10.5.5-focal
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: base2020
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - my-data:/var/lib/mysql
    networks:
      - app-network

  #PhpmyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - db
    tty: true
    ports:
      - "8080:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=base2020
      - PHP_UPLOAD_MAX_FILESIZE=100MB
      #- PMA_ARBITRARY=1
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  my-data:
